# config.yml
projects:
  - name: "dummy-web-production"
    repo: "https://github.com/ryouta3962/test_web.git" # ★ここを本物のGitHub URLにする
    branch: "main"
    trigger:
      type: "polling"
      interval: "30s" # 30秒ごとにGitHubを覗きに行く
    registry:
      server: "localhost:5000"