projects:
    - name: api-test-app
      repo: https://github.com/ryouta3962/test_web.git
      branch: main
      trigger:
        type: polling
        interval: 10m
      registry:
        server: localhost:5000
        username: ""
        password_env: ""