name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # GHCRへの書き込み権限を追加
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # GitHubが自動で用意してくれる鍵

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # タグを ghcr.io/ユーザー名/リポジトリ名:latest に設定
          tags: ghcr.io/${{ github.repository }}:latest